apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-jul18-1-gitops
  description: This is GitOps manifest for go-jul18-1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: go-jul18-1
    janus-idp.io/tekton: go-jul18-1
    backstage.io/kubernetes-id: go-jul18-1 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-jul18-1
